sonar.projectKey=Agusslo_actividad8_gestion
sonar.organization=agusslo

# Rutas de código y tests (ajustá si tus archivos están sueltos o en src)
sonar.sources=src
sonar.tests=tests

# Codificación
sonar.sourceEncoding=UTF-8

# Ruta del reporte de cobertura para evaluar el Quality Gate del 80%
sonar.javascript.lcov.reportPaths=coverage/lcov.info
